// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emrcipgnkhlniidjtzfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtcmNpcGdua2hsbmlpZGp0emZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDgxOTYsImV4cCI6MjA2OTgyNDE5Nn0.LVD9v7k66Bu77EO814l65Fo2pfKIoJZf4cFaCqwAbi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});